# Script to deploy on the Render Cloud Platform

name: Node.js CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{secrets.DEPLOY_HOOK_URL}}
        webhook_secret: ${{secrets.DEPLOY_HOOK_KEY}}
      
    - run: npm ci
    - run: npm test

    
    #- uses: bounceapp/render-action@0.6.0
    #  with:
     #   render-token: ${{secrets.RENDER_API_KEY}}
      #  github-token: ${{secrets.ACC_API_KEY}} #This is the Github token
       # service-id: "srv-cg9d9spmbg54mbeamdgg" # This id is unique for each loop
        #retries: 20
        #wait: 16000
        #sleep: 30000